import { z } from "zod";

export const ratingSchema = z.enum(["again", "hard", "good", "easy"]);
export type Rating = z.infer<typeof ratingSchema>;

// Language codes are data (the `languages` table), not schema. Keep this list
// in sync with what is seeded; it is only used for input validation.
export const languageCodeSchema = z.enum(["en", "nl"]);
export type LanguageCode = z.infer<typeof languageCodeSchema>;

// Adding a pack (or a single concept) to the user's active deck in a direction.
export const addToDeckSchema = z
  .object({
    fromLanguage: languageCodeSchema,
    toLanguage: languageCodeSchema,
  })
  .refine((v) => v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });
export type AddToDeckInput = z.infer<typeof addToDeckSchema>;

export const submitReviewSchema = z.object({
  userCardId: z.string().uuid(),
  // Generated by the client per answer; resubmitting the same id is a no-op.
  clientReviewId: z.string().uuid(),
  rating: ratingSchema,
  timeTakenMs: z.number().int().nonnegative().optional(),
});
export type SubmitReviewInput = z.infer<typeof submitReviewSchema>;

export const registerSchema = z.object({
  email: z.string().trim().toLowerCase().email().max(254),
  password: z.string().min(8).max(200),
});
export type RegisterInput = z.infer<typeof registerSchema>;

export const loginSchema = z.object({
  email: z.string().trim().toLowerCase().email().max(254),
  password: z.string().min(1).max(200),
});
export type LoginInput = z.infer<typeof loginSchema>;

export type PublicUser = { id: string; email: string };

// Optional direction for browsing: both languages or neither.
export const directionQuerySchema = z
  .object({
    fromLanguage: languageCodeSchema.optional(),
    toLanguage: languageCodeSchema.optional(),
  })
  .refine((v) => (v.fromLanguage === undefined) === (v.toLanguage === undefined), {
    message: "Provide both fromLanguage and toLanguage, or neither",
  })
  .refine((v) => v.fromLanguage === undefined || v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });

export const pageQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(1000).default(100),
  offset: z.coerce.number().int().min(0).default(0),
});

export const conceptSearchQuerySchema = z
  .object({
    q: z.string().trim().min(1).max(100),
    fromLanguage: languageCodeSchema,
    toLanguage: languageCodeSchema,
    limit: z.coerce.number().int().min(1).max(50).default(50),
    offset: z.coerce.number().int().min(0).default(0),
    // "1" leaves out words the signed-in user already has a card for.
    hideInDeck: z.enum(["0", "1"]).default("0"),
  })
  .refine((v) => v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });

// Narrowing and ordering the deck list: a word to search for, a stage
// ("learning" includes relearning), and a sort. Each sort has a natural
// direction used when `order` is left out (see DECK_SORT_DEFAULT_ORDER).
export const DECK_SORTS = ["added", "due", "status", "interval", "lapses", "alpha"] as const;
export type DeckSort = (typeof DECK_SORTS)[number];
export const DECK_SORT_DEFAULT_ORDER: Record<DeckSort, "asc" | "desc"> = {
  added: "desc", // newest first
  due: "asc", // soonest first; cards not yet studied always come last
  status: "asc", // new, learning, relearning, review
  interval: "desc", // longest first
  lapses: "desc", // most forgotten first
  alpha: "asc", // by the prompt word
};

export const deckFilterSchema = z.object({
  q: z.string().trim().max(100).optional(),
  state: z.enum(["new", "learning", "review"]).optional(),
  sort: z.enum(DECK_SORTS).default("added"),
  order: z.enum(["asc", "desc"]).optional(),
  // "1" keeps only cards whose opposite-direction card is not in the deck.
  missingMirror: z.enum(["0", "1"]).default("0"),
});

export const uuidParamSchema = z.object({ id: z.string().uuid() });

export type EntryView = {
  language: string;
  lemma: string;
  partOfSpeech: string | null;
  details: Record<string, unknown>;
};

export const studyQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
  // "1" starts the next session a little early (see EARLY_START_WINDOW_MS).
  early: z.enum(["0", "1"]).default("0"),
});

/**
 * The shortest time between study sessions. Cards still being learned (answered
 * Hard or Good, or just seen) are held back until this long after the last answer,
 * so each session is a distinct sitting rather than a trickle of minutes-long waits.
 */
export const SESSION_GAP_MS = 15 * 60 * 1000;
/** In the last stretch of that wait, the next session may be started early. */
export const EARLY_START_WINDOW_MS = 5 * 60 * 1000;

// Response shapes of the API (dates arrive as ISO strings over JSON).
export type CardStateName = "new" | "learning" | "review" | "relearning";

export type DeckSummary = {
  total: number;
  new: number;
  learning: number;
  review: number;
  relearning: number;
  dueNow: number;
};
export type DeckCardView = {
  id: string;
  conceptId: string;
  fromLanguage: string;
  toLanguage: string;
  state: CardStateName;
  dueAt: string;
  addedAt: string;
  intervalDays: number;
  lapses: number;
  lastReviewedAt: string | null;
  /** Whether the same word is also in the deck in the opposite direction. */
  hasMirror: boolean;
  front: EntryView[];
  back: EntryView[];
};
export type DeckResponse = {
  /** Totals for the direction, regardless of the search and stage filters. */
  summary: DeckSummary;
  cards: DeckCardView[];
  /** True when more cards match after this page. */
  hasMore: boolean;
  /** How many cards matching the search, stage and direction have no opposite-direction card yet. */
  mirrorable: number;
};
export type AddMirrorsResult = { added: number };

export type StudyCounts = { learning: number; review: number; new: number };
export type StudyCardView = {
  id: string;
  conceptId: string;
  fromLanguage: string;
  toLanguage: string;
  state: CardStateName;
  dueAt: string;
  front: EntryView[];
  back: EntryView[];
  sentences: { front: string[]; back: string[] };
};
export type StudyResponse = { now: string; counts: StudyCounts; cards: StudyCardView[] };

export type DirectionSummary = {
  fromLanguage: string;
  toLanguage: string;
  total: number;
  new: number;
  /** Learning and relearning. */
  learning: number;
  review: number;
  dueNow: number;
  /** When the next not-yet-due card in this direction comes due, if any. */
  nextDueAt: string | null;
  /**
   * What a study session in just this direction would offer right now. The daily
   * new-card limit is shared across directions, so `new` here can add up to more
   * than the whole-deck figure.
   */
  ready: { learning: number; review: number; new: number };
};

export type StatsResponse = {
  now: string;
  /** Answers submitted since the study day began (all directions). */
  reviewsToday: number;
  /** When the next card comes due in any direction. Null if none is scheduled. */
  nextDueAt: string | null;
  /** One row per direction the user has cards in. */
  directions: DirectionSummary[];
};

/**
 * The next session is held back until this time (SESSION_GAP_MS after the last answer),
 * when `count` cards will be ready. Null when nothing is being held back.
 */
export type NextSession = { at: string; count: number };

/** The dashboard's view of the study queue: how many cards of each kind, and what is coming. */
export type StudyCountsResponse = {
  now: string;
  counts: StudyCounts;
  nextSession: NextSession | null;
  /**
   * How many cards will be ready to study by the end of tomorrow's study day: those due
   * by then, plus the new cards tomorrow's daily limit will allow.
   */
  tomorrow: number;
};

export type ReviewResponse = {
  userCardId: string;
  state: CardStateName;
  dueAt: string;
  intervalDays: number;
  /** Server time of the answer; dueAt - reviewedAt is the wait until the card returns. */
  reviewedAt: string;
  replayed: boolean;
};

export type LanguageInfo = { code: string; name: string };

/**
 * What kind of pack it is, for browsing. Every pack has exactly one.
 * - common: the most frequent words, in order (the frequency bands and the starter pack)
 * - topic: words about a subject, such as food or travel
 * - verbs: verbs, grouped by what they do
 * - grammar: the small words that hold sentences together (pronouns, prepositions, ...)
 */
export const PACK_CATEGORIES = ["common", "topic", "verbs", "grammar"] as const;
export type PackCategory = (typeof PACK_CATEGORIES)[number];
export const PACK_CATEGORY_LABELS: Record<PackCategory, string> = {
  common: "Most common words",
  topic: "Topics",
  verbs: "Verbs",
  grammar: "Grammar words",
};

export type PackListItem = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  category: PackCategory;
  conceptCount: number;
  /** Present when a direction was requested. */
  availableCount?: number;
  /** Present when a direction was requested and the user is signed in. */
  addedCount?: number;
};

export type PackConceptView = {
  conceptId: string;
  position: number;
  entries: EntryView[];
  available?: boolean;
  inDeck?: boolean;
};

export type ConceptSearchResult = {
  conceptId: string;
  entries: EntryView[];
  inDeck?: boolean;
};
export type ConceptSearchResponse = {
  concepts: ConceptSearchResult[];
  /** True when more matches exist after this page. */
  hasMore: boolean;
};

export type PackDetailResponse = {
  pack: { id: string; slug: string; name: string; description: string | null };
  concepts: PackConceptView[];
};

export type AddPackResult = { added: number; alreadyInDeck: number; unavailable: number };
export type AddConceptResult = { added: number; alreadyInDeck: number };

export * from "./forms.js";
