import { z } from "zod";

export const ratingSchema = z.enum(["again", "hard", "good", "easy"]);
export type Rating = z.infer<typeof ratingSchema>;

// Language codes are data (the `languages` table), not schema. Keep this list
// in sync with what is seeded; it is only used for input validation.
export const languageCodeSchema = z.enum(["en", "nl"]);
export type LanguageCode = z.infer<typeof languageCodeSchema>;

// Adding a pack (or a single concept) to the user's active deck in a direction.
export const addToDeckSchema = z
  .object({
    fromLanguage: languageCodeSchema,
    toLanguage: languageCodeSchema,
  })
  .refine((v) => v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });
export type AddToDeckInput = z.infer<typeof addToDeckSchema>;

export const submitReviewSchema = z.object({
  userCardId: z.string().uuid(),
  // Generated by the client per answer; resubmitting the same id is a no-op.
  clientReviewId: z.string().uuid(),
  rating: ratingSchema,
  timeTakenMs: z.number().int().nonnegative().optional(),
});
export type SubmitReviewInput = z.infer<typeof submitReviewSchema>;

export const registerSchema = z.object({
  email: z.string().trim().toLowerCase().email().max(254),
  password: z.string().min(8).max(200),
});
export type RegisterInput = z.infer<typeof registerSchema>;

export const loginSchema = z.object({
  email: z.string().trim().toLowerCase().email().max(254),
  password: z.string().min(1).max(200),
});
export type LoginInput = z.infer<typeof loginSchema>;

export type PublicUser = { id: string; email: string };

// Optional direction for browsing: both languages or neither.
export const directionQuerySchema = z
  .object({
    fromLanguage: languageCodeSchema.optional(),
    toLanguage: languageCodeSchema.optional(),
  })
  .refine((v) => (v.fromLanguage === undefined) === (v.toLanguage === undefined), {
    message: "Provide both fromLanguage and toLanguage, or neither",
  })
  .refine((v) => v.fromLanguage === undefined || v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });

export const pageQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(1000).default(100),
  offset: z.coerce.number().int().min(0).default(0),
});

export const conceptSearchQuerySchema = z
  .object({
    q: z.string().trim().min(1).max(100),
    fromLanguage: languageCodeSchema,
    toLanguage: languageCodeSchema,
    limit: z.coerce.number().int().min(1).max(50).default(50),
    offset: z.coerce.number().int().min(0).default(0),
    // "1" leaves out words the signed-in user already has a card for.
    hideInDeck: z.enum(["0", "1"]).default("0"),
  })
  .refine((v) => v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });

export const uuidParamSchema = z.object({ id: z.string().uuid() });

export type EntryView = {
  language: string;
  lemma: string;
  partOfSpeech: string | null;
  details: Record<string, unknown>;
};

export const studyQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
});

// Response shapes of the API (dates arrive as ISO strings over JSON).
export type CardStateName = "new" | "learning" | "review" | "relearning";

export type DeckSummary = {
  total: number;
  new: number;
  learning: number;
  review: number;
  relearning: number;
  dueNow: number;
};
export type DeckResponse = { summary: DeckSummary };

export type StudyCounts = { learning: number; review: number; new: number };
export type StudyCardView = {
  id: string;
  conceptId: string;
  fromLanguage: string;
  toLanguage: string;
  state: CardStateName;
  dueAt: string;
  front: EntryView[];
  back: EntryView[];
  sentences: { front: string[]; back: string[] };
};
export type StudyResponse = { now: string; counts: StudyCounts; cards: StudyCardView[] };

export type DirectionSummary = {
  fromLanguage: string;
  toLanguage: string;
  total: number;
  new: number;
  /** Learning and relearning. */
  learning: number;
  review: number;
  dueNow: number;
  /** When the next not-yet-due card in this direction comes due, if any. */
  nextDueAt: string | null;
};

export type StatsResponse = {
  now: string;
  /** Answers submitted since the study day began (all directions). */
  reviewsToday: number;
  /** When the next card comes due in any direction. Null if none is scheduled. */
  nextDueAt: string | null;
  /** One row per direction the user has cards in. */
  directions: DirectionSummary[];
};

export type ReviewResponse = {
  userCardId: string;
  state: CardStateName;
  dueAt: string;
  intervalDays: number;
  /** Server time of the answer; dueAt - reviewedAt is the wait until the card returns. */
  reviewedAt: string;
  replayed: boolean;
};

export type LanguageInfo = { code: string; name: string };

export type PackListItem = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  conceptCount: number;
  /** Present when a direction was requested. */
  availableCount?: number;
  /** Present when a direction was requested and the user is signed in. */
  addedCount?: number;
};

export type PackConceptView = {
  conceptId: string;
  position: number;
  entries: EntryView[];
  available?: boolean;
  inDeck?: boolean;
};

export type ConceptSearchResult = {
  conceptId: string;
  entries: EntryView[];
  inDeck?: boolean;
};
export type ConceptSearchResponse = {
  concepts: ConceptSearchResult[];
  /** True when more matches exist after this page. */
  hasMore: boolean;
};

export type PackDetailResponse = {
  pack: { id: string; slug: string; name: string; description: string | null };
  concepts: PackConceptView[];
};

export type AddPackResult = { added: number; alreadyInDeck: number; unavailable: number };
export type AddConceptResult = { added: number; alreadyInDeck: number };

export * from "./forms.js";
