import { z } from "zod";
import { PAIR_PATTERN, languageCodeSchema, pairKey, pairLanguages, type LanguageCode } from "./languages.js";

export const ratingSchema = z.enum(["again", "hard", "good", "easy"]);
export type Rating = z.infer<typeof ratingSchema>;

// The supported languages (and the schema for their codes) are defined in languages.ts.

// Adding a pack (or a single concept) to the user's active deck in a direction.
export const addToDeckSchema = z
  .object({
    fromLanguage: languageCodeSchema,
    toLanguage: languageCodeSchema,
    // Also add the opposite direction (the same words, studied the other way around).
    bothDirections: z.boolean().optional(),
  })
  .refine((v) => v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });
export type AddToDeckInput = z.infer<typeof addToDeckSchema>;

// A problem someone found with a word's card: a wrong translation, missing or wrong forms, an odd
// example sentence. About the word (concept), in the direction it was shown.
export const REPORT_REASONS = ["translation", "forms", "sentence", "other"] as const;
export type ReportReason = (typeof REPORT_REASONS)[number];
export const REPORT_REASON_LABELS: Record<ReportReason, string> = {
  translation: "The translation is wrong",
  forms: "The word forms are wrong",
  sentence: "An example sentence is wrong",
  other: "Something else",
};
export const REPORT_NOTE_MAX = 1000;
export const reportCardSchema = z
  .object({
    fromLanguage: languageCodeSchema,
    toLanguage: languageCodeSchema,
    reason: z.enum(REPORT_REASONS),
    note: z.string().trim().max(REPORT_NOTE_MAX).default(""),
  })
  .refine((v) => v.reason !== "other" || v.note.length > 0, {
    message: "Please say what is wrong",
    path: ["note"],
  });
export type ReportCardInput = z.input<typeof reportCardSchema>;

export const submitReviewSchema = z.object({
  userCardId: z.string().uuid(),
  // Generated by the client per answer; resubmitting the same id is a no-op.
  clientReviewId: z.string().uuid(),
  rating: ratingSchema,
  timeTakenMs: z.number().int().nonnegative().optional(),
});
export type SubmitReviewInput = z.infer<typeof submitReviewSchema>;

/** Whether `tz` is an IANA time zone name this runtime knows ("Europe/Amsterdam"). */
export function isValidTimeZone(tz: string): boolean {
  try {
    new Intl.DateTimeFormat("en-US", { timeZone: tz });
    return true;
  } catch {
    return false;
  }
}

/** The longest name a user can give. */
export const NAME_MAX = 60;

export const registerSchema = z.object({
  email: z.string().trim().toLowerCase().email().max(254),
  password: z.string().min(8).max(200),
  // Optional. Shown in place of the email once given; empty counts as not given.
  name: z.string().trim().max(NAME_MAX).optional(),
  // The browser's time zone, so the study day is right from the start. An unknown
  // value is ignored (the account keeps the default) rather than blocking sign-up.
  timezone: z.string().max(64).optional(),
});
export type RegisterInput = z.infer<typeof registerSchema>;

export const loginSchema = z.object({
  email: z.string().trim().toLowerCase().email().max(254),
  password: z.string().min(1).max(200),
});
export type LoginInput = z.infer<typeof loginSchema>;

export const changePasswordSchema = z.object({
  currentPassword: z.string().min(1).max(200),
  newPassword: z.string().min(8).max(200),
});
export type ChangePasswordInput = z.infer<typeof changePasswordSchema>;

export const changeEmailSchema = z.object({
  email: z.string().trim().toLowerCase().email().max(254),
  // The current password, to confirm it is really the owner.
  password: z.string().min(1).max(200),
});
export type ChangeEmailInput = z.infer<typeof changeEmailSchema>;

export const deleteAccountSchema = z.object({ password: z.string().min(1).max(200) });
export type DeleteAccountInput = z.infer<typeof deleteAccountSchema>;

export type PublicUser = {
  id: string;
  email: string;
  name: string | null;
  /** What the user is learning, prompt language first. Each language pair is a deck of its own. */
  direction: { from: LanguageCode; to: LanguageCode };
};

/** The most new cards a day a user can ask for. */
export const DAILY_NEW_CARD_MAX = 200;

export const updateSettingsSchema = z
  .object({
    // An empty name clears it.
    name: z.string().trim().max(NAME_MAX).optional(),
    timezone: z.string().max(64).refine(isValidTimeZone, "Unknown time zone").optional(),
    dailyNewCardLimit: z.number().int().min(0).max(DAILY_NEW_CARD_MAX).optional(),
    // What the study cards show.
    showSentences: z.boolean().optional(),
    showForms: z.boolean().optional(),
    // What the user is learning: the pages and decks they see are for this pair of languages.
    direction: z
      .object({ from: languageCodeSchema, to: languageCodeSchema })
      .refine((d) => d.from !== d.to, "The two languages must differ")
      .optional(),
  })
  .refine(
    (v) =>
      v.name !== undefined ||
      v.timezone !== undefined ||
      v.dailyNewCardLimit !== undefined ||
      v.showSentences !== undefined ||
      v.showForms !== undefined ||
      v.direction !== undefined,
    { message: "Provide a setting to change" },
  );
export type UpdateSettingsInput = z.infer<typeof updateSettingsSchema>;

export type Settings = {
  email: string;
  /** What to call the user; null when they have not given one. */
  name: string | null;
  /** IANA name; the study day starts at 04:00 here. */
  timezone: string;
  /** New cards introduced per study day, for each language pair. */
  dailyNewCardLimit: number;
  /** Show the example sentences on study cards. */
  showSentences: boolean;
  /** Show the word forms (plural, verb forms) with the answer. */
  showForms: boolean;
  /** What the user is learning, prompt language first. */
  direction: { from: LanguageCode; to: LanguageCode };
};

// Optional direction for browsing: both languages or neither.
export const directionQuerySchema = z
  .object({
    fromLanguage: languageCodeSchema.optional(),
    toLanguage: languageCodeSchema.optional(),
  })
  .refine((v) => (v.fromLanguage === undefined) === (v.toLanguage === undefined), {
    message: "Provide both fromLanguage and toLanguage, or neither",
  })
  .refine((v) => v.fromLanguage === undefined || v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });

// What part of the deck a request is about: everything, one language pair (both of its directions)
// or one direction. `pair` is a pair key such as "en-nl", in either order. It is only a filter, so
// a pair of languages the app does not know simply matches nothing. A direction together with a
// pair must be one of that pair's directions.
const pairParam = z
  .string()
  .regex(PAIR_PATTERN, "pair must be two language codes joined by a hyphen, such as en-nl");

// Just the language pair, for what is about a whole deck and not part of one: studying and the
// stats. Anything else in the query is ignored.
export const pairQuerySchema = z
  .object({ pair: pairParam.optional() })
  .refine((v) => v.pair === undefined || pairLanguages(v.pair)[0] !== pairLanguages(v.pair)[1], {
    message: "a pair needs two different languages",
  })
  .transform((v) => (v.pair === undefined ? {} : { pair: pairKey(...pairLanguages(v.pair)) }));

export const scopeQuerySchema = z
  .object({
    fromLanguage: languageCodeSchema.optional(),
    toLanguage: languageCodeSchema.optional(),
    pair: pairParam.optional(),
  })
  .refine((v) => (v.fromLanguage === undefined) === (v.toLanguage === undefined), {
    message: "Provide both fromLanguage and toLanguage, or neither",
  })
  .refine((v) => v.fromLanguage === undefined || v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  })
  .refine((v) => v.pair === undefined || pairLanguages(v.pair)[0] !== pairLanguages(v.pair)[1], {
    message: "a pair needs two different languages",
  })
  .refine(
    (v) =>
      v.pair === undefined ||
      v.fromLanguage === undefined ||
      pairKey(...pairLanguages(v.pair)) === pairKey(v.fromLanguage, v.toLanguage!),
    { message: "the direction is not one of the pair's directions" },
  )
  .transform((v) => (v.pair === undefined ? v : { ...v, pair: pairKey(...pairLanguages(v.pair)) }));
export type Scope = {
  fromLanguage?: string | undefined;
  toLanguage?: string | undefined;
  /** A pair key, such as "en-nl". */
  pair?: string | undefined;
};

export const pageQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(1000).default(100),
  offset: z.coerce.number().int().min(0).default(0),
});

export const conceptCardQuerySchema = z
  .object({ fromLanguage: languageCodeSchema, toLanguage: languageCodeSchema })
  .refine((v) => v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });

export const conceptSearchQuerySchema = z
  .object({
    q: z.string().trim().min(1).max(100),
    fromLanguage: languageCodeSchema,
    toLanguage: languageCodeSchema,
    limit: z.coerce.number().int().min(1).max(50).default(50),
    offset: z.coerce.number().int().min(0).default(0),
    // "1" leaves out words the signed-in user already has a card for.
    hideInDeck: z.enum(["0", "1"]).default("0"),
  })
  .refine((v) => v.fromLanguage !== v.toLanguage, {
    message: "fromLanguage and toLanguage must differ",
  });

// Narrowing and ordering the deck list: a word to search for, a stage
// ("learning" includes relearning), and a sort. Each sort has a natural
// direction used when `order` is left out (see DECK_SORT_DEFAULT_ORDER).
export const DECK_SORTS = ["added", "due", "status", "alpha"] as const;
export type DeckSort = (typeof DECK_SORTS)[number];
export const DECK_SORT_DEFAULT_ORDER: Record<DeckSort, "asc" | "desc"> = {
  added: "desc", // newest first
  due: "asc", // soonest first; cards not yet studied always come last
  status: "asc", // new, learning, relearning, review
  alpha: "asc", // by the prompt word
};

export const deckFilterSchema = z.object({
  q: z.string().trim().max(100).optional(),
  state: z.enum(["new", "learning", "review"]).optional(),
  sort: z.enum(DECK_SORTS).default("added"),
  order: z.enum(["asc", "desc"]).optional(),
});

export const uuidParamSchema = z.object({ id: z.string().uuid() });

export type EntryView = {
  language: string;
  lemma: string;
  partOfSpeech: string | null;
  details: Record<string, unknown>;
};

export const studyQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
  // "1" starts the next session a little early (see EARLY_START_WINDOW_MS).
  early: z.enum(["0", "1"]).default("0"),
});

/**
 * The shortest time between study sessions. Cards still being learned (answered
 * Hard or Good, or just seen) are held back until this long after the last answer,
 * so each session is a distinct sitting rather than a trickle of minutes-long waits.
 */
export const SESSION_GAP_MS = 15 * 60 * 1000;
/** In the last stretch of that wait, the next session may be started early. */
export const EARLY_START_WINDOW_MS = 5 * 60 * 1000;

// Response shapes of the API (dates arrive as ISO strings over JSON).
export type CardStateName = "new" | "learning" | "review" | "relearning";

export type DeckSummary = {
  total: number;
  new: number;
  learning: number;
  review: number;
  relearning: number;
  dueNow: number;
};
export type DeckCardView = {
  id: string;
  conceptId: string;
  fromLanguage: string;
  toLanguage: string;
  state: CardStateName;
  dueAt: string;
  addedAt: string;
  intervalDays: number;
  lapses: number;
  lastReviewedAt: string | null;
  front: EntryView[];
  back: EntryView[];
};
/** A word as a card in a direction, whether or not it is in anyone's deck: both sides and all sentences. */
export type ConceptCardDetail = {
  conceptId: string;
  fromLanguage: string;
  toLanguage: string;
  front: EntryView[];
  back: EntryView[];
  sentences: { front: string[]; back: string[] };
};

/** One card of the deck in full: both sides' words and forms, and all their example sentences. */
export type DeckCardDetail = {
  card: DeckCardView;
  sentences: { front: string[]; back: string[] };
};

export type DeckResponse = {
  /** Totals for the direction, regardless of the search and stage filters. */
  summary: DeckSummary;
  cards: DeckCardView[];
  /** True when more cards match after this page. */
  hasMore: boolean;
};

export type StudyCounts = { learning: number; review: number; new: number };
export type StudyCardView = {
  id: string;
  conceptId: string;
  fromLanguage: string;
  toLanguage: string;
  state: CardStateName;
  dueAt: string;
  front: EntryView[];
  back: EntryView[];
  sentences: { front: string[]; back: string[] };
};
export type StudyResponse = {
  now: string;
  counts: StudyCounts;
  cards: StudyCardView[];
  /** The user has never answered a card, in any language pair: this is their very first session. */
  firstSession: boolean;
  /**
   * New cards in the deck beyond the ones in `counts.new`, held back by the daily limit. A new card
   * answered Good or Easy on its first look does not use the limit up, so each one brings another of
   * these into today's session.
   */
  moreNew: number;
};

export type DirectionSummary = {
  fromLanguage: string;
  toLanguage: string;
  total: number;
  new: number;
  /** Learning and relearning. */
  learning: number;
  review: number;
  dueNow: number;
  /** When the next not-yet-due card in this direction comes due, if any. */
  nextDueAt: string | null;
};

export type StatsResponse = {
  now: string;
  /** Answers submitted since the study day began (all directions). */
  reviewsToday: number;
  /** When the next card comes due in any direction. Null if none is scheduled. */
  nextDueAt: string | null;
  /** One row per direction the user has cards in. */
  directions: DirectionSummary[];
};

/**
 * The next session is held back until this time (SESSION_GAP_MS after the last answer),
 * when `count` cards will be ready. Null when nothing is being held back.
 */
export type NextSession = { at: string; count: number };

/** The dashboard's view of the study queue: how many cards of each kind, and what is coming. */
export type StudyCountsResponse = {
  now: string;
  counts: StudyCounts;
  /** There are new cards in the deck, but today's daily new-card limit has been reached. */
  newLimitReached: boolean;
  nextSession: NextSession | null;
  /**
   * How many cards will be ready to study by the end of tomorrow's study day: those due
   * by then, plus the new cards tomorrow's daily limit will allow.
   */
  tomorrow: number;
};

export type ReviewResponse = {
  userCardId: string;
  state: CardStateName;
  dueAt: string;
  intervalDays: number;
  /** Server time of the answer; dueAt - reviewedAt is the wait until the card returns. */
  reviewedAt: string;
  replayed: boolean;
};

export type LanguageInfo = { code: string; name: string };

/**
 * What kind of pack it is, for browsing. Every pack has exactly one.
 * - common: the most frequent words, in order (the frequency bands and the starter pack)
 * - topic: words about a subject, such as food or travel
 * - verbs: verbs, grouped by what they do
 * - grammar: the small words that hold sentences together (pronouns, prepositions, ...)
 */
export const PACK_CATEGORIES = ["common", "topic", "verbs", "grammar"] as const;
export type PackCategory = (typeof PACK_CATEGORIES)[number];
export const PACK_CATEGORY_LABELS: Record<PackCategory, string> = {
  common: "Most common words",
  topic: "Topics",
  verbs: "Verbs",
  grammar: "Grammar words",
};

export type PackListItem = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  category: PackCategory;
  /** The language the pack teaches, or null if it suits any language. */
  target: LanguageCode | null;
  conceptCount: number;
  /** Present when a direction was requested. */
  availableCount?: number;
  /** Present when a direction was requested and the user is signed in. */
  addedCount?: number;
};

export type PackConceptView = {
  conceptId: string;
  position: number;
  entries: EntryView[];
  available?: boolean;
  inDeck?: boolean;
};

export type ConceptSearchResult = {
  conceptId: string;
  entries: EntryView[];
  inDeck?: boolean;
};
export type ConceptSearchResponse = {
  concepts: ConceptSearchResult[];
  /** True when more matches exist after this page. */
  hasMore: boolean;
};

export type PackDetailResponse = {
  pack: { id: string; slug: string; name: string; description: string | null };
  concepts: PackConceptView[];
};

export type AddPackResult = { added: number; alreadyInDeck: number; unavailable: number };
export type AddConceptResult = { added: number; alreadyInDeck: number };

export * from "./forms.js";
export * from "./languages.js";
